// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Data;

#nullable disable

namespace CreditService.Migrations
{
    [DbContext(typeof(CreditDbContext))]
    partial class CreditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditService.Domain.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("accountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("interestRate")
                        .HasColumnType("real");

                    b.Property<double>("principal")
                        .HasColumnType("double precision");

                    b.Property<double>("remainingAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<Guid>("tarrifId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("CreditService.Domain.CreditTariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("interestRate")
                        .HasColumnType("real");

                    b.Property<double>("maxAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("maxTerm")
                        .HasColumnType("integer");

                    b.Property<double>("minAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("minTerm")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
